---
# tasks

- name: Install necessary packages
  import_tasks: packages.yml

- name: Apply required SELinux booleans
  import_tasks: selinux_boolean.yml

- name: Create the users for kojid
  import_tasks: users.yml

- name: Configure kojid
  import_tasks: config.yml
  when: not kojid_shared_builders | bool

- name: Configure shared kojid
  import_tasks: shared/config_shared.yml
  when: kojid_shared_builders | bool
